# JSON examples and exercise
****
+ get familiar with packages for dealing with JSON
+ study examples with JSON strings and files 
+ work on exercise to be completed and submitted 
****
+ reference: http://pandas.pydata.org/pandas-docs/stable/io.html#io-json-reader
****

## imports for Python, Pandas

In [1]:
import pandas as pd

In [2]:
import json
from pandas.io.json import json_normalize

## JSON example, with string

+ demonstrates creation of normalized dataframes (tables) from nested json string
+ source: http://pandas.pydata.org/pandas-docs/stable/io.html#normalization

In [3]:
# define json string
data = [{'state': 'Florida', 
         'shortname': 'FL',
         'info': {'governor': 'Rick Scott'},
         'counties': [{'name': 'Dade', 'population': 12345},
                      {'name': 'Broward', 'population': 40000},
                      {'name': 'Palm Beach', 'population': 60000}]},
        {'state': 'Ohio',
         'shortname': 'OH',
         'info': {'governor': 'John Kasich'},
         'counties': [{'name': 'Summit', 'population': 1234},
                      {'name': 'Cuyahoga', 'population': 1337}]}]

In [4]:
# use normalization to create tables from nested element
json_normalize(data, 'counties')

         name  population
0        Dade       12345
1     Broward       40000
2  Palm Beach       60000
3      Summit        1234
4    Cuyahoga        1337

In [5]:
# further populate tables created from nested element
json_normalize(data, 'counties', ['state', 'shortname', ['info', 'governor']])

         name  population    state shortname info.governor
0        Dade       12345  Florida        FL    Rick Scott
1     Broward       40000  Florida        FL    Rick Scott
2  Palm Beach       60000  Florida        FL    Rick Scott
3      Summit        1234     Ohio        OH   John Kasich
4    Cuyahoga        1337     Ohio        OH   John Kasich

****
## JSON example, with file

+ demonstrates reading in a json file as a string and as a table
+ uses small sample file containing data about projects funded by the World Bank

In [6]:
# load json as string
json.load((open('data/world_bank_projects_less.json')))

[{'_id': {'$oid': '52b213b38594d8a2be17c780'},
  'approvalfy': 1999,
  'board_approval_month': 'November',
  'boardapprovaldate': '2013-11-12T00:00:00Z',
  'borrower': 'FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA',
  'closingdate': '2018-07-07T00:00:00Z',
  'country_namecode': 'Federal Democratic Republic of Ethiopia!$!ET',
  'countrycode': 'ET',
  'countryname': 'Federal Democratic Republic of Ethiopia',
  'countryshortname': 'Ethiopia',
  'docty': 'Project Information Document,Indigenous Peoples Plan,Project Information Document',
  'envassesmentcategorycode': 'C',
  'grantamt': 0,
  'ibrdcommamt': 0,
  'id': 'P129828',
  'idacommamt': 130000000,
  'impagency': 'MINISTRY OF EDUCATION',
  'lendinginstr': 'Investment Project Financing',
  'lendinginstrtype': 'IN',
  'lendprojectcost': 550000000,
  'majorsector_percent': [{'Name': 'Education', 'Percent': 46},
   {'Name': 'Education', 'Percent': 26},
   {'Name': 'Public Administration, Law, and Justice', 'Percent': 16},
   {'Name': 'Education', 'Percent': 12}],
  'mjsector_namecode': [{'name': 'Education', 'code': 'EX'},
   {'name': 'Education', 'code': 'EX'},
   {'name': 'Public Administration, Law, and Justice', 'code': 'BX'},
   {'name': 'Education', 'code': 'EX'}],
  'mjtheme': ['Human development'],
  'mjtheme_namecode': [{'name': 'Human development', 'code': '8'},
   {'name': '', 'code': '11'}],
  'mjthemecode': '8,11',
  'prodline': 'PE',
  'prodlinetext': 'IBRD/IDA',
  'productlinetype': 'L',
  'project_abstract': {'cdata': 'The development objective of the Second Phase of General Education Quality Improvement Project for Ethiopia is to improve learning conditions in primary and secondary schools and strengthen institutions at different levels of educational administration. The project has six components. The first component is curriculum, textbooks, assessment, examinations, and inspection. This component will support improvement of learning conditions in grades KG-12 by providing increased access to teaching and learning materials and through improvements to the curriculum by assessing the strengths and weaknesses of the current curriculum. This component has following four sub-components: (i) curriculum reform and implementation; (ii) teaching and learning materials; (iii) assessment and examinations; and (iv) inspection. The second component is teacher development program (TDP). This component will support improvements in learning conditions in both primary and secondary schools by advancing the quality of teaching in general education through: (a) enhancing the training of pre-service teachers in teacher education institutions; and (b) improving the quality of in-service teacher training. This component has following three sub-components: (i) pre-service teacher training; (ii) in-service teacher training; and (iii) licensing and relicensing of teachers and school leaders. The third component is school improvement plan. This component will support the strengthening of school planning in order to improve learning outcomes, and to partly fund the school improvement plans through school grants. It has following two sub-components: (i) school improvement plan; and (ii) school grants. The fourth component is management and capacity building, including education management information systems (EMIS). This component will support management and capacity building aspect of the project. This component has following three sub-components: (i) capacity building for education planning and management; (ii) capacity building for school planning and management; and (iii) EMIS. The fifth component is improving the quality of learning and teaching in secondary schools and universities through the use of information and communications technology (ICT). It has following five sub-components: (i) national policy and institution for ICT in general education; (ii) national ICT infrastructure improvement plan for general education; (iii) develop an integrated monitoring, evaluation, and learning system specifically for the ICT component; (iv) teacher professional development in the use of ICT; and (v) provision of limited number of e-Braille display readers with the possibility to scale up to all secondary education schools based on the successful implementation and usage of the readers. The sixth component is program coordination, monitoring and evaluation, and communication. It will support institutional strengthening by developing capacities in all aspects of program coordination, monitoring and evaluation; a new sub-component on communications will support information sharing for better management and accountability. It has following three sub-components: (i) program coordination; (ii) monitoring and evaluation (M and E); and (iii) communication.'},
  'project_name': 'Ethiopia General Education Quality Improvement Project II',
  'projectdocs': [{'DocTypeDesc': 'Project Information Document (PID),  Vol.',
    'DocType': 'PID',
    'EntityID': '090224b081e545fb_1_0',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b081e545fb_1_0',
    'DocDate': '28-AUG-2013'},
   {'DocTypeDesc': 'Indigenous Peoples Plan (IP),  Vol.1 of 1',
    'DocType': 'IP',
    'EntityID': '000442464_20130920111729',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20130920111729',
    'DocDate': '01-JUL-2013'},
   {'DocTypeDesc': 'Project Information Document (PID),  Vol.',
    'DocType': 'PID',
    'EntityID': '090224b0817b19e2_1_0',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b0817b19e2_1_0',
    'DocDate': '22-NOV-2012'}],
  'projectfinancialtype': 'IDA',
  'projectstatusdisplay': 'Active',
  'regionname': 'Africa',
  'sector': [{'Name': 'Primary education'},
   {'Name': 'Secondary education'},
   {'Name': 'Public administration- Other social services'},
   {'Name': 'Tertiary education'}],
  'sector1': {'Name': 'Primary education', 'Percent': 46},
  'sector2': {'Name': 'Secondary education', 'Percent': 26},
  'sector3': {'Name': 'Public administration- Other social services',
   'Percent': 16},
  'sector4': {'Name': 'Tertiary education', 'Percent': 12},
  'sector_namecode': [{'name': 'Primary education', 'code': 'EP'},
   {'name': 'Secondary education', 'code': 'ES'},
   {'name': 'Public administration- Other social services', 'code': 'BS'},
   {'name': 'Tertiary education', 'code': 'ET'}],
  'sectorcode': 'ET,BS,ES,EP',
  'source': 'IBRD',
  'status': 'Active',
  'supplementprojectflg': 'N',
  'theme1': {'Name': 'Education for all', 'Percent': 100},
  'theme_namecode': [{'name': 'Education for all', 'code': '65'}],
  'themecode': '65',
  'totalamt': 130000000,
  'totalcommamt': 130000000,
  'url': 'http://www.worldbank.org/projects/P129828/ethiopia-general-education-quality-improvement-project-ii?lang=en'},
 {'_id': {'$oid': '52b213b38594d8a2be17c781'},
  'approvalfy': 2015,
  'board_approval_month': 'November',
  'boardapprovaldate': '2013-11-04T00:00:00Z',
  'borrower': 'GOVERNMENT OF TUNISIA',
  'country_namecode': 'Republic of Tunisia!$!TN',
  'countrycode': 'TN',
  'countryname': 'Republic of Tunisia',
  'countryshortname': 'Tunisia',
  'docty': 'Project Information Document,Integrated Safeguards Data Sheet,Integrated Safeguards Data Sheet,Project Information Document,Integrated Safeguards Data Sheet,Project Information Document',
  'envassesmentcategorycode': 'C',
  'grantamt': 4700000,
  'ibrdcommamt': 0,
  'id': 'P144674',
  'idacommamt': 0,
  'impagency': 'MINISTRY OF FINANCE',
  'lendinginstr': 'Specific Investment Loan',
  'lendinginstrtype': 'IN',
  'lendprojectcost': 5700000,
  'majorsector_percent': [{'Name': 'Public Administration, Law, and Justice',
    'Percent': 70},
   {'Name': 'Public Administration, Law, and Justice', 'Percent': 30}],
  'mjsector_namecode': [{'name': 'Public Administration, Law, and Justice',
    'code': 'BX'},
   {'name': 'Public Administration, Law, and Justice', 'code': 'BX'}],
  'mjtheme': ['Economic management', 'Social protection and risk management'],
  'mjtheme_namecode': [{'name': 'Economic management', 'code': '1'},
   {'name': 'Social protection and risk management', 'code': '6'}],
  'mjthemecode': '1,6',
  'prodline': 'RE',
  'prodlinetext': 'Recipient Executed Activities',
  'productlinetype': 'L',
  'project_name': 'TN: DTF Social Protection Reforms Support',
  'projectdocs': [{'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocType': 'PID',
    'EntityID': '000333037_20131024115616',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131024115616',
    'DocDate': '29-MAR-2013'},
   {'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocType': 'ISDS',
    'EntityID': '000356161_20131024151611',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20131024151611',
    'DocDate': '29-MAR-2013'},
   {'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocType': 'ISDS',
    'EntityID': '000442464_20131031112136',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20131031112136',
    'DocDate': '29-MAR-2013'},
   {'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocType': 'PID',
    'EntityID': '000333037_20131031105716',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131031105716',
    'DocDate': '29-MAR-2013'},
   {'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocType': 'ISDS',
    'EntityID': '000356161_20130305113209',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113209',
    'DocDate': '16-JAN-2013'},
   {'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocType': 'PID',
    'EntityID': '000356161_20130305113716',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113716',
    'DocDate': '16-JAN-2013'}],
  'projectfinancialtype': 'OTHER',
  'projectstatusdisplay': 'Active',
  'regionname': 'Middle East and North Africa',
  'sector': [{'Name': 'Public administration- Other social services'},
   {'Name': 'General public administration sector'}],
  'sector1': {'Name': 'Public administration- Other social services',
   'Percent': 70},
  'sector2': {'Name': 'General public administration sector', 'Percent': 30},
  'sector_namecode': [{'name': 'Public administration- Other social services',
    'code': 'BS'},
   {'name': 'General public administration sector', 'code': 'BZ'}],
  'sectorcode': 'BZ,BS',
  'source': 'IBRD',
  'status': 'Active',
  'supplementprojectflg': 'N',
  'theme1': {'Name': 'Other economic management', 'Percent': 30},
  'theme_namecode': [{'name': 'Other economic management', 'code': '24'},
   {'name': 'Social safety nets', 'code': '54'}],
  'themecode': '54,24',
  'totalamt': 0,
  'totalcommamt': 4700000,
  'url': 'http://www.worldbank.org/projects/P144674?lang=en'}]

In [7]:
# load as Pandas dataframe
sample_json_df = pd.read_json('data/world_bank_projects_less.json')
sample_json_df

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{'Name': 'Education for all', 'Percent': 100}","[{'name': 'Education for all', 'code': '65'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{'Name': 'Other economic management', 'Percent...","[{'name': 'Other economic management', 'code':...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en

****
## JSON exercise

Using data in file 'data/world_bank_projects.json' and the techniques demonstrated above,
1. Find the 10 countries with most projects
2. Find the top 10 major project themes (using column 'mjtheme_namecode')
3. In 2. above you will notice that some entries have only the code and the name is missing. Create a dataframe with the missing names filled in.

### Loading in smaller JSON to inspect the columns

In [8]:
#load in the smaller sample JSON to inspect columns. Use relative paths.
short_string = json.load((open('data/world_bank_projects_less.json')))

In [9]:
short_string

[{'_id': {'$oid': '52b213b38594d8a2be17c780'},
  'approvalfy': 1999,
  'board_approval_month': 'November',
  'boardapprovaldate': '2013-11-12T00:00:00Z',
  'borrower': 'FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA',
  'closingdate': '2018-07-07T00:00:00Z',
  'country_namecode': 'Federal Democratic Republic of Ethiopia!$!ET',
  'countrycode': 'ET',
  'countryname': 'Federal Democratic Republic of Ethiopia',
  'countryshortname': 'Ethiopia',
  'docty': 'Project Information Document,Indigenous Peoples Plan,Project Information Document',
  'envassesmentcategorycode': 'C',
  'grantamt': 0,
  'ibrdcommamt': 0,
  'id': 'P129828',
  'idacommamt': 130000000,
  'impagency': 'MINISTRY OF EDUCATION',
  'lendinginstr': 'Investment Project Financing',
  'lendinginstrtype': 'IN',
  'lendprojectcost': 550000000,
  'majorsector_percent': [{'Name': 'Education', 'Percent': 46},
   {'Name': 'Education', 'Percent': 26},
   {'Name': 'Public Administration, Law, and Justice', 'Percent': 16},
   {'Name': 'Education', 'Percent': 12}],
  'mjsector_namecode': [{'name': 'Education', 'code': 'EX'},
   {'name': 'Education', 'code': 'EX'},
   {'name': 'Public Administration, Law, and Justice', 'code': 'BX'},
   {'name': 'Education', 'code': 'EX'}],
  'mjtheme': ['Human development'],
  'mjtheme_namecode': [{'name': 'Human development', 'code': '8'},
   {'name': '', 'code': '11'}],
  'mjthemecode': '8,11',
  'prodline': 'PE',
  'prodlinetext': 'IBRD/IDA',
  'productlinetype': 'L',
  'project_abstract': {'cdata': 'The development objective of the Second Phase of General Education Quality Improvement Project for Ethiopia is to improve learning conditions in primary and secondary schools and strengthen institutions at different levels of educational administration. The project has six components. The first component is curriculum, textbooks, assessment, examinations, and inspection. This component will support improvement of learning conditions in grades KG-12 by providing increased access to teaching and learning materials and through improvements to the curriculum by assessing the strengths and weaknesses of the current curriculum. This component has following four sub-components: (i) curriculum reform and implementation; (ii) teaching and learning materials; (iii) assessment and examinations; and (iv) inspection. The second component is teacher development program (TDP). This component will support improvements in learning conditions in both primary and secondary schools by advancing the quality of teaching in general education through: (a) enhancing the training of pre-service teachers in teacher education institutions; and (b) improving the quality of in-service teacher training. This component has following three sub-components: (i) pre-service teacher training; (ii) in-service teacher training; and (iii) licensing and relicensing of teachers and school leaders. The third component is school improvement plan. This component will support the strengthening of school planning in order to improve learning outcomes, and to partly fund the school improvement plans through school grants. It has following two sub-components: (i) school improvement plan; and (ii) school grants. The fourth component is management and capacity building, including education management information systems (EMIS). This component will support management and capacity building aspect of the project. This component has following three sub-components: (i) capacity building for education planning and management; (ii) capacity building for school planning and management; and (iii) EMIS. The fifth component is improving the quality of learning and teaching in secondary schools and universities through the use of information and communications technology (ICT). It has following five sub-components: (i) national policy and institution for ICT in general education; (ii) national ICT infrastructure improvement plan for general education; (iii) develop an integrated monitoring, evaluation, and learning system specifically for the ICT component; (iv) teacher professional development in the use of ICT; and (v) provision of limited number of e-Braille display readers with the possibility to scale up to all secondary education schools based on the successful implementation and usage of the readers. The sixth component is program coordination, monitoring and evaluation, and communication. It will support institutional strengthening by developing capacities in all aspects of program coordination, monitoring and evaluation; a new sub-component on communications will support information sharing for better management and accountability. It has following three sub-components: (i) program coordination; (ii) monitoring and evaluation (M and E); and (iii) communication.'},
  'project_name': 'Ethiopia General Education Quality Improvement Project II',
  'projectdocs': [{'DocTypeDesc': 'Project Information Document (PID),  Vol.',
    'DocType': 'PID',
    'EntityID': '090224b081e545fb_1_0',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b081e545fb_1_0',
    'DocDate': '28-AUG-2013'},
   {'DocTypeDesc': 'Indigenous Peoples Plan (IP),  Vol.1 of 1',
    'DocType': 'IP',
    'EntityID': '000442464_20130920111729',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20130920111729',
    'DocDate': '01-JUL-2013'},
   {'DocTypeDesc': 'Project Information Document (PID),  Vol.',
    'DocType': 'PID',
    'EntityID': '090224b0817b19e2_1_0',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=090224b0817b19e2_1_0',
    'DocDate': '22-NOV-2012'}],
  'projectfinancialtype': 'IDA',
  'projectstatusdisplay': 'Active',
  'regionname': 'Africa',
  'sector': [{'Name': 'Primary education'},
   {'Name': 'Secondary education'},
   {'Name': 'Public administration- Other social services'},
   {'Name': 'Tertiary education'}],
  'sector1': {'Name': 'Primary education', 'Percent': 46},
  'sector2': {'Name': 'Secondary education', 'Percent': 26},
  'sector3': {'Name': 'Public administration- Other social services',
   'Percent': 16},
  'sector4': {'Name': 'Tertiary education', 'Percent': 12},
  'sector_namecode': [{'name': 'Primary education', 'code': 'EP'},
   {'name': 'Secondary education', 'code': 'ES'},
   {'name': 'Public administration- Other social services', 'code': 'BS'},
   {'name': 'Tertiary education', 'code': 'ET'}],
  'sectorcode': 'ET,BS,ES,EP',
  'source': 'IBRD',
  'status': 'Active',
  'supplementprojectflg': 'N',
  'theme1': {'Name': 'Education for all', 'Percent': 100},
  'theme_namecode': [{'name': 'Education for all', 'code': '65'}],
  'themecode': '65',
  'totalamt': 130000000,
  'totalcommamt': 130000000,
  'url': 'http://www.worldbank.org/projects/P129828/ethiopia-general-education-quality-improvement-project-ii?lang=en'},
 {'_id': {'$oid': '52b213b38594d8a2be17c781'},
  'approvalfy': 2015,
  'board_approval_month': 'November',
  'boardapprovaldate': '2013-11-04T00:00:00Z',
  'borrower': 'GOVERNMENT OF TUNISIA',
  'country_namecode': 'Republic of Tunisia!$!TN',
  'countrycode': 'TN',
  'countryname': 'Republic of Tunisia',
  'countryshortname': 'Tunisia',
  'docty': 'Project Information Document,Integrated Safeguards Data Sheet,Integrated Safeguards Data Sheet,Project Information Document,Integrated Safeguards Data Sheet,Project Information Document',
  'envassesmentcategorycode': 'C',
  'grantamt': 4700000,
  'ibrdcommamt': 0,
  'id': 'P144674',
  'idacommamt': 0,
  'impagency': 'MINISTRY OF FINANCE',
  'lendinginstr': 'Specific Investment Loan',
  'lendinginstrtype': 'IN',
  'lendprojectcost': 5700000,
  'majorsector_percent': [{'Name': 'Public Administration, Law, and Justice',
    'Percent': 70},
   {'Name': 'Public Administration, Law, and Justice', 'Percent': 30}],
  'mjsector_namecode': [{'name': 'Public Administration, Law, and Justice',
    'code': 'BX'},
   {'name': 'Public Administration, Law, and Justice', 'code': 'BX'}],
  'mjtheme': ['Economic management', 'Social protection and risk management'],
  'mjtheme_namecode': [{'name': 'Economic management', 'code': '1'},
   {'name': 'Social protection and risk management', 'code': '6'}],
  'mjthemecode': '1,6',
  'prodline': 'RE',
  'prodlinetext': 'Recipient Executed Activities',
  'productlinetype': 'L',
  'project_name': 'TN: DTF Social Protection Reforms Support',
  'projectdocs': [{'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocType': 'PID',
    'EntityID': '000333037_20131024115616',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131024115616',
    'DocDate': '29-MAR-2013'},
   {'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocType': 'ISDS',
    'EntityID': '000356161_20131024151611',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20131024151611',
    'DocDate': '29-MAR-2013'},
   {'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocType': 'ISDS',
    'EntityID': '000442464_20131031112136',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000442464_20131031112136',
    'DocDate': '29-MAR-2013'},
   {'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocType': 'PID',
    'EntityID': '000333037_20131031105716',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000333037_20131031105716',
    'DocDate': '29-MAR-2013'},
   {'DocTypeDesc': 'Integrated Safeguards Data Sheet (ISDS),  Vol.1 of 1',
    'DocType': 'ISDS',
    'EntityID': '000356161_20130305113209',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113209',
    'DocDate': '16-JAN-2013'},
   {'DocTypeDesc': 'Project Information Document (PID),  Vol.1 of 1',
    'DocType': 'PID',
    'EntityID': '000356161_20130305113716',
    'DocURL': 'http://www-wds.worldbank.org/servlet/WDSServlet?pcont=details&eid=000356161_20130305113716',
    'DocDate': '16-JAN-2013'}],
  'projectfinancialtype': 'OTHER',
  'projectstatusdisplay': 'Active',
  'regionname': 'Middle East and North Africa',
  'sector': [{'Name': 'Public administration- Other social services'},
   {'Name': 'General public administration sector'}],
  'sector1': {'Name': 'Public administration- Other social services',
   'Percent': 70},
  'sector2': {'Name': 'General public administration sector', 'Percent': 30},
  'sector_namecode': [{'name': 'Public administration- Other social services',
    'code': 'BS'},
   {'name': 'General public administration sector', 'code': 'BZ'}],
  'sectorcode': 'BZ,BS',
  'source': 'IBRD',
  'status': 'Active',
  'supplementprojectflg': 'N',
  'theme1': {'Name': 'Other economic management', 'Percent': 30},
  'theme_namecode': [{'name': 'Other economic management', 'code': '24'},
   {'name': 'Social safety nets', 'code': '54'}],
  'themecode': '54,24',
  'totalamt': 0,
  'totalcommamt': 4700000,
  'url': 'http://www.worldbank.org/projects/P144674?lang=en'}]

### Loading in the full file

In [10]:
#load in the full file
full_file = pd.read_json('data/world_bank_projects.json')

### Question 1 - Find the 10 countries with most projects

In [11]:
#group by countries and print out 10 countries with the most projects
country_df = full_file.groupby('countryshortname').id.nunique().sort_values(ascending = False)
country_df.head(10)

countryshortname
Indonesia             19
China                 19
Vietnam               17
India                 16
Yemen, Republic of    13
Nepal                 12
Bangladesh            12
Morocco               12
Mozambique            11
Africa                11
Name: id, dtype: int64

### Question 2 - Find the top 10 major project themes

In [12]:
full_string = json.load((open('data/world_bank_projects.json')))

In [13]:
#Use JSON Normalize to print out top 10 most common project themes
pt = json_normalize(full_string, 'mjtheme_namecode', errors='ignore').groupby('name').size().sort_values(ascending = False)
pt.head(11)

name
Environment and natural resources management    223
Rural development                               202
Human development                               197
Public sector governance                        184
Social protection and risk management           158
Financial and private sector development        130
                                                122
Social dev/gender/inclusion                     119
Trade and integration                            72
Urban development                                47
Economic management                              33
dtype: int64

### Question 3 - There are a significant amount of blanks so we need to fill in and then re-do the above list

In [14]:
print(full_file['mjtheme_namecode'].head(30))

0     [{'code': '8', 'name': 'Human development'}, {...
1     [{'code': '1', 'name': 'Economic management'},...
2     [{'code': '5', 'name': 'Trade and integration'...
3     [{'code': '7', 'name': 'Social dev/gender/incl...
4     [{'code': '5', 'name': 'Trade and integration'...
5     [{'code': '6', 'name': 'Social protection and ...
6     [{'code': '2', 'name': 'Public sector governan...
7     [{'code': '11', 'name': 'Environment and natur...
8     [{'code': '10', 'name': 'Rural development'}, ...
9     [{'code': '2', 'name': 'Public sector governan...
10    [{'code': '10', 'name': 'Rural development'}, ...
11    [{'code': '10', 'name': 'Rural development'}, ...
12                          [{'code': '4', 'name': ''}]
13    [{'code': '5', 'name': 'Trade and integration'...
14    [{'code': '6', 'name': 'Social protection and ...
15    [{'code': '10', 'name': 'Rural development'}, ...
16    [{'code': '10', 'name': 'Rural development'}, ...
17    [{'code': '8', 'name': 'Human development'}, {...
18    [{'code': '8', 'name': 'Human development'}, {...
19    [{'code': '2', 'name': 'Public sector governan...
20    [{'code': '7', 'name': 'Social dev/gender/incl...
21    [{'code': '9', 'name': 'Urban development'}, {...
22    [{'code': '7', 'name': 'Social dev/gender/incl...
23    [{'code': '8', 'name': 'Human development'}, {...
24    [{'code': '10', 'name': 'Rural development'}, ...
25    [{'code': '11', 'name': 'Environment and natur...
26    [{'code': '4', 'name': 'Financial and private ...
27    [{'code': '11', 'name': 'Environment and natur...
28    [{'code': '10', 'name': 'Rural development'}, ...
29    [{'code': '7', 'name': 'Social dev/gender/incl...
Name: mjtheme_namecode, dtype: object

In [15]:
import numpy as np

In [16]:
#Create the same DF as df_pt, set empty values to NaN, then replace all NaN values by doing a forward fill
pt2 = json_normalize(full_string, 'mjtheme_namecode', errors='ignore')
pt2 = pd.DataFrame(pt2.replace('', np.NaN))

In [17]:
pt2.head()

  code                                   name
0    8                      Human development
1   11                                    NaN
2    1                    Economic management
3    6  Social protection and risk management
4    5                  Trade and integration

#### Get a dictionary of what code maps to which name and then merge the DFs to fill in the blanks

In [18]:
#create new DF. Drop NaNs and duplicates.
pt3 = pt2.dropna()
pt3 = pt3.drop_duplicates()
pt3

    code                                          name
0      8                             Human development
2      1                           Economic management
3      6         Social protection and risk management
4      5                         Trade and integration
5      2                      Public sector governance
6     11  Environment and natural resources management
8      7                   Social dev/gender/inclusion
11     4      Financial and private sector development
18    10                             Rural development
53     9                             Urban development
252    3                                   Rule of law

In [19]:
pt4 = pt3.merge(pt2, how='outer')
pt4.head(20)

   code               name
0     8  Human development
1     8  Human development
2     8  Human development
3     8  Human development
4     8  Human development
5     8  Human development
6     8  Human development
7     8  Human development
8     8  Human development
9     8  Human development
10    8  Human development
11    8  Human development
12    8  Human development
13    8  Human development
14    8  Human development
15    8  Human development
16    8  Human development
17    8  Human development
18    8  Human development
19    8  Human development

In [20]:
pt5 = pt4.groupby('code')
pt5.head(10)

     code                                   name
0       8                      Human development
1       8                      Human development
2       8                      Human development
3       8                      Human development
4       8                      Human development
5       8                      Human development
6       8                      Human development
7       8                      Human development
8       8                      Human development
9       8                      Human development
197     1                    Economic management
198     1                    Economic management
199     1                    Economic management
200     1                    Economic management
201     1                    Economic management
202     1                    Economic management
203     1                    Economic management
204     1                    Economic management
205     1                    Economic management
206     1                    Economic management
230     6  Social protection and risk management
231     6  Social protection and risk management
232     6  Social protection and risk management
233     6  Social protection and risk management
234     6  Social protection and risk management
235     6  Social protection and risk management
236     6  Social protection and risk management
237     6  Social protection and risk management
238     6  Social protection and risk management
239     6  Social protection and risk management
...   ...                                    ...
1116   10                      Rural development
1117   10                      Rural development
1118   10                      Rural development
1119   10                      Rural development
1120   10                      Rural development
1121   10                      Rural development
1122   10                      Rural development
1123   10                      Rural development
1124   10                      Rural development
1125   10                      Rural development
1318    9                      Urban development
1319    9                      Urban development
1320    9                      Urban development
1321    9                      Urban development
1322    9                      Urban development
1323    9                      Urban development
1324    9                      Urban development
1325    9                      Urban development
1326    9                      Urban development
1327    9                      Urban development
1365    3                            Rule of law
1366    3                            Rule of law
1367    3                            Rule of law
1368    3                            Rule of law
1369    3                            Rule of law
1370    3                            Rule of law
1371    3                            Rule of law
1372    3                            Rule of law
1373    3                            Rule of law
1374    3                            Rule of law

[110 rows x 2 columns]

In [21]:
#Fill in blank values using forward fill as the DF is grouped by the appropriate code
pt5 = pt5.fillna(method='ffill')

In [22]:
#check shape before dropping NaN values
pt4.shape

(1499, 2)

In [23]:
#drop NaN values
pt5.dropna()

                       name
0         Human development
1         Human development
2         Human development
3         Human development
4         Human development
5         Human development
6         Human development
7         Human development
8         Human development
9         Human development
10        Human development
11        Human development
12        Human development
13        Human development
14        Human development
15        Human development
16        Human development
17        Human development
18        Human development
19        Human development
20        Human development
21        Human development
22        Human development
23        Human development
24        Human development
25        Human development
26        Human development
27        Human development
28        Human development
29        Human development
...                     ...
1469      Rural development
1470      Rural development
1471      Rural development
1472      Rural development
1473      Rural development
1474      Rural development
1475      Rural development
1476      Rural development
1477      Rural development
1478      Rural development
1479      Rural development
1480      Rural development
1481      Rural development
1482      Rural development
1483  Trade and integration
1484  Trade and integration
1485  Trade and integration
1486  Trade and integration
1487  Trade and integration
1488    Economic management
1489    Economic management
1490    Economic management
1491    Economic management
1492    Economic management
1493      Urban development
1494      Urban development
1495      Urban development
1496            Rule of law
1497            Rule of law
1498            Rule of law

[1499 rows x 1 columns]

In [24]:
#Check shape after dropping NaN values
pt2.shape

(1499, 2)

#### Properly answer Question 2 - What are the top 10 project themes?

In [25]:
pt5.groupby('name').size().sort_values(ascending = False).head(10)

name
Environment and natural resources management    250
Rural development                               216
Human development                               210
Public sector governance                        199
Social protection and risk management           168
Financial and private sector development        146
Social dev/gender/inclusion                     130
Trade and integration                            77
Urban development                                50
Economic management                              38
dtype: int64